pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Docker Build') {
            steps {
                dir('SignalRChat') {
                    sh "docker build -t my-dotnet-app:latest ."
                }
            }
        }
        stage('Ansible Deploy') {
            steps {
                dir('SignalRChat') {
                    sh "ansible-playbook deploy.yml"
                }
            }
        }
    }
}
